// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240712140116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("API.Models.Aluno", b =>
                {
                    b.Property<string>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = "6d091456-5a2f-4b5a-98fc-f1a3b50a627d",
                            Altura = 1.75,
                            CriadoEm = new DateTime(2024, 7, 12, 11, 1, 15, 509, DateTimeKind.Local).AddTicks(2852),
                            Nome = "João",
                            Peso = 70.0,
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            AlunoId = "bfe4e7dc-81e4-4e47-a67b-d4fbf3e124bd",
                            Altura = 1.6499999999999999,
                            CriadoEm = new DateTime(2024, 7, 12, 11, 1, 15, 509, DateTimeKind.Local).AddTicks(2858),
                            Nome = "Maria",
                            Peso = 60.0,
                            Sobrenome = "Oliveira"
                        });
                });

            modelBuilder.Entity("API.Models.IMC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorIMC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("IMCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 1.75m,
                            AlunoId = "6d091456-5a2f-4b5a-98fc-f1a3b50a627d",
                            Classificacao = "Normal",
                            DataCriacao = new DateTime(2024, 7, 12, 14, 1, 15, 509, DateTimeKind.Utc).AddTicks(3037),
                            Peso = 70.0m,
                            ValorIMC = 22.857142857142857142857142857m
                        },
                        new
                        {
                            Id = 2,
                            Altura = 1.65m,
                            AlunoId = "bfe4e7dc-81e4-4e47-a67b-d4fbf3e124bd",
                            Classificacao = "Normal",
                            DataCriacao = new DateTime(2024, 7, 12, 14, 1, 15, 509, DateTimeKind.Utc).AddTicks(3040),
                            Peso = 60.0m,
                            ValorIMC = 22.038567493112947658402203857m
                        });
                });

            modelBuilder.Entity("API.Models.IMC", b =>
                {
                    b.HasOne("API.Models.Aluno", "Aluno")
                        .WithMany("IMCs")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("API.Models.Aluno", b =>
                {
                    b.Navigation("IMCs");
                });
#pragma warning restore 612, 618
        }
    }
}
